### ISSUE TITLE
Test failed : Error 1001: JavaScript profiling failed

### ISSUE THREAD

**Issue by caiuspupus** [gmetais/YellowLabTools#100]
Hi,

I ran some tests of some websites and I got this error for the following:

- http://www.vosgesmatin.fr
- http://www.bienpublic.com/
- http://www.ledauphine.com/

For information purpose, I ran tests on other web tools for these sites and they worked well.

Thanks in advance for your help on this.

**Comment by gmetais** [comment]
Congratulations, this is the 100th issue :)

I'll have a look at the problem when I get a moment.

Just like your other errors (#99), it's working fine on my local instance.
The common problem with these 3 websites is the huge amount of DOM access. It might be a clue: the tool can't handle that many JavaScript to profile.


If you work on these sites, you should definitely optimize JavaScript. I've measured that the JS alone takes 5.3 seconds while loading http://www.ledauphine.com on my (fast) computer... I let you imagine what's happening on a slow computer or a mobile device.

**Comment by caiuspupus** [comment]
Thanks for the previous ones that made te the 100th :)

I know that JS among other things is to be optimized, that is why I'm looking for as many tools as I can to have as many details as I can.

Is it possible for you to give me the detailed result of these tests from your local machine (same goes for the 3 of the 99th issue)

Thanks for your answer !

**Comment by gmetais** [comment]
Here we go!

dna.fr: http://yellowlab.tools/result/e6gi9akeey
lejsl.com: http://yellowlab.tools/result/e6gi9f3g5w
lalsace.fr: http://yellowlab.tools/result/e6gi9juy73
vosgesmatin.fr: http://yellowlab.tools/result/e6gi9r4w69
bienpublic.com: http://yellowlab.tools/result/e6gi9x930u
ledauphine.com: http://yellowlab.tools/result/e6gia2jz4d

You might face long page loads on these urls. Especially on the JS Timeline, where your browser will probably take a minute or two to generate the profiler's table, you'll have to be patient. That would need to be optimized too :)

Don't hesitate if you need more help!

**Comment by caiuspupus** [comment]
Thanks a lot !

**Comment by DanielAguirre** [comment]
I have the same error, but when  i try it in the online tools gives me the results but it takes longer than normal

There is a way to configure the local version to wait longer to get the result

**Comment by gmetais** [comment]
Hi @DanielAguirre,

The default timeout is 45s.
Are you saying that the issue occurs when there is a timeout?

**Comment by DanielAguirre** [comment]
i have tested using phantomas and shows me a timeout error and  when increase the timeout the results is ok

**Comment by gmetais** [comment]
Error 1001 is a YLT only error. It is related to the in-depth javascript profiling done by YLT. Phantomas can't have it.

Would you be able to give me the url of your webpage?

**Comment by DanielAguirre** [comment]
Sorry i'm not enable to share the URL

**Comment by gmetais** [comment]
I understand.

**Comment by gmetais** [comment]
There is a new topic for 1001 errors: #170. I'm not reporting the errors from this thread as I can't reproduce them anymore.
