### ISSUE TITLE
Allow user to input a HTML file, like the W3C validator

### ISSUE THREAD

**Issue by mlorant** [gmetais/YellowLabTools#110]
The real part of a website can sometimes be accessible only through a web session (e.g : Facebook, Twitter where the front-page is quite simple compared to the real "homepage" when the user is connected).

Unlike the [W3C validator](https://validator.w3.org/#validate_by_input), it would be nice to be able to submit a HTML to validate. This has limitation (CSS/JS links in the file should be accessible without login to have a complete report), but it could highlight HTML problems that you do not have in a simple login page.

**Comment by gmetais** [comment]
Hi @mlorant,

Thank you for your suggestion, but I'm afraid this is too far from the way YLT works. It's a real browser, opening an URL, and switching to a static file analyzer would be a lot of work!

I suggest you use the **cookie** setting (advanced settings). You find and copy the session cookie from your browser into the cookie field in YLT. You should then be able to analyze the webpage as long as the session does not expire.

You might also like http://mir.aculo.us/dom-monster/ which is an HTML analyzer that works inside the browser.

I'm closing the issue, sorry :/
