### ISSUE TITLE
Error 1003: Phantomas not returning

### ISSUE THREAD

**Issue by euskadi31** [gmetais/YellowLabTools#113]
Url: http://yellowlab.tools/queue/e7h1q8gzv0
Tested url:   https://www.kokoroe.fr

~~~
Test failed
Error 1003: Phantomas not returning
~~~

**Comment by gmetais** [comment]
Hi @euskadi31,

I think I found the reason why it fails. Your page overrides Date.now and sets it to an integer. YellowLabTools needs this function.

Here is a bit of code from your page:
```js
window.Date.now = window.Date.now() || function() {
    return +new Date
}
```

I could fix it somewhere on YLT's side, but Phantomas also uses it and I can't tell you how easy it can be fixed. As it is an extremely rare case, could you fix it on your side?

**Comment by euskadi31** [comment]
Oupss...

Thank you, I fixed it, the release will be tomorrow ;)
