### ISSUE TITLE
Error 1003: Phantomas not returning

### ISSUE THREAD

**Issue by jurgenzz** [gmetais/YellowLabTools#123]
Tested url:   http://chapelizodmusicschool.com

Url: http://yellowlab.tools/queue/e8z5wxx5cg

**Comment by gmetais** [comment]
Hi, and thank you for filling this issue.

This bug means that Phantomas loaded the webpage but stopped responding. After waiting for 150s, YLT kills Phantomas and throws this error.

Now I need to understand why :)

**Comment by jurgenzz** [comment]
Cool, good luck! 

If you need anything from my side, like any information about website, feel free to ask!

**Comment by gmetais** [comment]
Not reproducing the error. I'm closing.
