### ISSUE TITLE
Inconsistent number of DOM manipulation errors

### ISSUE THREAD

**Issue by danra** [gmetais/YellowLabTools#124]
Hi!

I'm getting inconsistent results in DOM manipulations category - so inconsistent that this specific category can change the site's grade from C to F. Is there maybe a test which run an inconsistent number of times?

See http://yellowlab.tools/result/e90cztsiij

P.S. Cannot unfortunately fix these manipulations which are mostly due to the ThemePunch slider.

Cheers,
Dan

**Comment by gmetais** [comment]
Hi @danra 

This happens sometimes, when things happen periodically in the page (such as Ajax polling or timers) and Phantomas doesn't know when to stop recording things. So it keeps recording until reaching the timeout, which is set to 25 seconds. You can see it in the "JS Timeline" view.

I'll give a closer look to the ending conditions and try to find a way to force Phantomas to stop recording when nothing interesting happens.

**Comment by gmetais** [comment]
Hi @danra,

Since the last release v1.9.2, I fixed a bug which prevented Phantomas to know when the page load was finished.

DOM manipulations count seems to be much more consistent on your website now!
