### ISSUE TITLE
False report of empty inline style(?)

### ISSUE THREAD

**Issue by danra** [gmetais/YellowLabTools#125]
The tool reports a single empty inline style tag, but I can't see it neither in my html nor in any CSS validator. Unfortunately there is no reference in the tool to the location of the problematic tag.

http://yellowlab.tools/result/e90cztsiij/rule/cssParsingErrors

Ideas?

Thanks,
Dan

**Comment by gmetais** [comment]
The analyze of stylesheets is done after the page is completely loaded. If you can't find the style in the original HTML, it means it was added by the JS. You'll be able to spot it with your browser's DOM inspector.

I'll see if I can remove empty inline styles from the parsing errors.

**Comment by danra** [comment]
Actually I did inspect the DOM and didn't see any empty style. Though maybe it's due to the dynamically changing themepunch toolbar, meaning it appeared later.

**Comment by gmetais** [comment]
Removing empty inline styles is not as easy as I thought. It has to be done in Phantomas, and I'm not sure it is worth the pain.

Closing, sorry :/
