### ISSUE TITLE
Error 1002: missing Phantomas metrics

### ISSUE THREAD

**Issue by anhtuangai** [gmetais/YellowLabTools#129]
Hi Gaël, I tried Yellow Lab Tools several time on http://lefigaro.fr and it does not work.
Error 1002: missing Phantomas metrics
FYI it works with http://www.lefigaro.fr/
Redirection is probably not well taken into account.

**Comment by gmetais** [comment]
Hi @anhtuangai,

The problem doesn't seem to be about the redirection. It looks like Phantomas is having difficulties with the website and fails most of the time (not always). I'll try to dig deeper when I have more time!
