### ISSUE TITLE
phantomas: (254) Page loading failed

### ISSUE THREAD

**Issue by beidiefische** [gmetais/YellowLabTools#130]
hi @ll

node Downloads/YellowLabTools-phantomjs2/node_modules/phantomas/bin/phantomas.js --version
phantomas v1.13.0

Test on Linux bash:
node node_modules/phantomas/bin/phantomas.js --ignore-ssl-errors=true https://myintranetsite.html
it works fine
node node_modules/phantomas/bin/phantomas.js https://myintranetsite.html
running in error
phantomas: (254) Page loading failed

on phantomas.js
replace
.describe('ignore-ssl-errors', 'ignores SSL errors, such as expired or self-signed certificate errors')
with 
.describe('ignore-ssl-errors', 'ignores SSL errors, such as expired or self-signed certificate errors').default('ignore-ssl-errors', 'true')

run test on bash again, give a result:

node /opt/YellowLabTools/node_modules/phantomas/bin/phantomas.js https://myintranetsite.html
Debug: Fontconfig error: Cannot load default config file
Debug: Fontconfig error: Cannot load default config file
phantomas v1.13.0 metrics for <https://myintranetsite.html>:

* requests: 36
* gzipRequests: 23
* postRequests: 0
* httpsRequests: 36
* notFound: 0
* bodySize: 710171 bytes
* contentLength: 710171 bytes
....

Run with Yellow Lab Tools, on localhost:8383 give a result:

Tested url:   https://myintranetsite.html
Test failed

Error 254: page loading failed in PhantomJS

my questions: 
there is a Yellow Lab Tools a config that overrides my attitude?
What do I have where to enter , so it will not happen again?

**Comment by gmetais** [comment]
Hi,

By default YLT uses PhantomJS 1.9. It is known to cause problems with some HTTPS domains.
Switching YLT to PhantomJS 2 should resolve the problem. You can do it by changing `engine` to `webkit2` in the config file `server_config/settings.json`.

It is not activated by default, because PhantomJS 2 mode only works on Linux for the moment.

Can you tell me if it fixes your problem?

**Comment by beidiefische** [comment]
Hi

my settings:
user@debian:~/Downloads/YellowLabTools-phantomjs2$ cat server_config/settings.json
{
    "serverPort": 8383,
    "phantomasEngine": "webkit2",
    "googleAnalyticsId": "",

    "authorizedKeys": {
        
    },
    "maxAnonymousRunsPerDay": 99999999,
    "maxAnonymousCallsPerDay": 99999999
}

my result, it is the same
user@debian:~/Downloads/YellowLabTools-phantomjs2$ node bin/server.js 
Listening on port 8383
Sending response without waiting.
Test failed for URL: https://myintranetsite.html
Error: 254

**Comment by gmetais** [comment]
The `ignore-ssl-errors` can be added here: https://github.com/gmetais/YellowLabTools/blob/master/lib/tools/phantomas/phantomasWrapper.js#L34

simply like this: 
```
'ignore-ssl-errors': true,
```

I thought it was already true by default.

**Comment by beidiefische** [comment]
Perfect. ;) That helped . Many thanks!

**Comment by gmetais** [comment]
I should maybe add it by default in YLT.
Can you tell me if you intranet has a properly set certificate?

**Comment by beidiefische** [comment]
-- Can you tell me if you intranet has a properly set certificate?
was exactly do you mean? 

I go through an authentication server. pPublic, can be accessed via a root CA . What i trust.

**Comment by gmetais** [comment]
Well I'm not a certificate specialist, but sometimes intranet websites use some self-signed certificates, making browsers ask if you really want to trust the website.

**Comment by beidiefische** [comment]
yes, this is a self-signed certificate, which must be trusted by the browser. Is there an option, in your tool to import the selt-signed root CA?

**Comment by gmetais** [comment]
Thank you for the answer, I understand now!
No, it's not possible to import a certificate.
