### ISSUE TITLE
Inconsistent number of request 

### ISSUE THREAD

**Issue by fyoudine** [gmetais/YellowLabTools#131]
Hi, I tried to install ylt on 3 differents computers:  my mac, à centos server, and an ubuntu and each one gives a différent result for the samedi URL with à different number of request which are less than the real number of resquest. Any idea on how to have always the same résult ?

**Comment by gmetais** [comment]
Hi!

Does your website load some ads or third parties, that could change on each load?
Does your website make some asynchronous calls after the end of the loading, that could sometimes be triggered before YLT ends and sometimes after?
Do you see any JS errors in the results?

**Comment by fyoudine** [comment]
Hi and thanks for the quick answer.

I tried with a simple page with only 9 request (if you check through a web
development tool)
The page has no interest in term of improvement needs but it's a good
exemple.

http://yellowlab.tools/result/e9pdgpchhs

But on yellowlab and my server there is only 8 whereas 9 on my localhost.
The missing request is a js (swfobject.js) that is called in the head of
html.
Is there a way to see the waterfall ?

Regards.
Franck.

**Comment by gmetais** [comment]
Hi Franck,
Could you please try to upgrade your server to the new v1.9.2?
