### ISSUE TITLE
Enhancement : show the number of XMLHTTPRequest that are not asynchronous

### ISSUE THREAD

**Issue by jpvincent** [gmetais/YellowLabTools#138]
It is a bad practice to make synchronous XHR, because it blocks the browser as long as the query has not arrived. It is even marked as deprecated by the specifications.
Though the threshold should be 1 : have an error when a synchronous XHR is detected

Ex : 	xhttp.open('GET', xmlLink, false);
The 3rd argument should be left by default to true

**Comment by gmetais** [comment]
Great idea!
Do you mind opening an issue for this new metric in https://github.com/macbre/phantomas ?

**Comment by gmetais** [comment]
Fixed by #178.
