### ISSUE TITLE
XML report error

### ISSUE THREAD

**Issue by fpaterno** [gmetais/YellowLabTools#141]
Hi @gmetais,

On yellowlabtools 1.9.3,  this message appears when option --reporter with xml is used : 
[TypeError: Cannot read property '_name' of null]

**Comment by gmetais** [comment]
Hi Florent!

I'm off for one month far from my computer. It would be very cool if someone could find a fix and send a pull-request!

**Comment by gmetais** [comment]
Closed by #145. Will be available in the next release.
