### ISSUE TITLE
Error install ERR! phantomjs2@2.0.0-alpha

### ISSUE THREAD

**Issue by Grafs** [gmetais/YellowLabTools#142]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! phantomjs2@2.0.0-alpha install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs2@2.0.0-alpha install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs2
npm ERR! There is likely additional logging output above.

Installs separately npm install -g phantomjs  everything is OK
The install in package does not work, return error

**Comment by gaelftven** [comment]
Hi,

Thank you for reporting the bug. It might be related to the recent release of PhantomJS 2.1.

I'm currently far from my computer, for 3 more weeks so I can't act.

Could you please try to clone the project, update the Phantomas dependency to its latest version 1.14 in package.json, then npm install?

**Comment by Grafs** [comment]
I cloned project. The error is repeated.
It turned out only install and set global PhantomJS and Fantomas and copying them to a local folder project

**Comment by gmetais** [comment]
Hi @Grafs!

Could you please try again with YLT v1.10?
