### ISSUE TITLE
Proxy pac url support

### ISSUE THREAD

**Issue by raghulraj** [gmetais/YellowLabTools#143]
Hi @gmetais,
I have question on proxy pac. We access our internal websites by setting up proxy pac in browser. Is it possible to pass proxy pac as param in yellowlabtools execution? We would like to host yellowlabtools as private. I was going through this issue mentioned in Phantomjs github page. https://github.com/ariya/phantomjs/issues/10834.

Is there any workaround for this? 

Thanks,
Raghul

**Comment by gmetais** [comment]
Same issue as https://github.com/gmetais/YellowLabTools/issues/78. Closing this one.
