### ISSUE TITLE
Different page load speed locally and through online tools

### ISSUE THREAD

**Issue by denstepa** [gmetais/YellowLabTools#153]
What could cause different page load speed, and also other metrics when running locally through npm package and online/(or api) ?
Through online tool we get around 46 points now, and npm package shows 98.
Do you have an idea what could cause that ?

**Comment by gmetais** [comment]
It shouldn't, but there are few things that could cause this:
 - the public instance is hosted in the US, maybe the website detects another country and redirects it to a different language than on your computer.
 - there's some kind of timeout on your computer
 - your computer is behind a proxy and fails to access the website
 - the tool's installation failed on your computer
 - some kind of bug...

I would need more information to answer your question. Do you want to send me your website url privately by email?

**Comment by gmetais** [comment]
Closing for now. Please tell me if you need more help!

**Comment by denstepa** [comment]
we've just using service via api for now
website is https://www.inkitt.com/
i can also provide you more details if needed

**Comment by gmetais** [comment]
I'm having the same score on the public instance and locally.

Could you please try to `npm uninstall`, then re-install and check that there's no error? It could be a problem with `imagemin` not installing correctly. If so, you need to install `libjpeg`.
