### ISSUE TITLE
Remove universal selectors rule

### ISSUE THREAD

**Issue by mattijsbliek** [gmetais/YellowLabTools#155]
The test says universal selectors are the most expensive selectors. And while that’s true it will only become an issue in really extreme cases, such as when having thousands of DOM elements on a page.

I consider selectors such as `.selector > *:first-child` or `[role="button"]` very useful and good practice. I’d be hard pressed to find a better alternative without resorting to adding classes or elements, and making my code less maintainable.

Also see this article by Ben Frain, including the comments from Webkit engineer Benjamin Poulain:
https://benfrain.com/css-performance-revisited-selectors-bloat-expensive-styles/

**Comment by GaetanBt** [comment]
I think your first example is not really representative of your need, you could get rid of the universal selector and write `.selector > :first-child` which is pretty much the same.

**Comment by mattijsbliek** [comment]
Good point. That's more of a style preference though, performance will be the same regardless.

**Comment by GaetanBt** [comment]
Yup :)

**Comment by gmetais** [comment]
Hi,

I think you convinced me. I'll probably remove it in a future version.

What about the **Complex attributes selector** rule? http://yellowlab.tools/result/eesnvsnuel/rule/cssComplexSelectorsByAttribute

**Comment by mattijsbliek** [comment]
I would be in favor of removing that rule. When using these kind of selectors, you usually have a good reason to do so. It's pretty hard to end up with something like `.foo[type$=bar]` accidentally. Something like `a[href*=twiter.com] { background-image: url('https://twitter.com/favicon.ico') }` would be a perfectly valid use case in my opinion.

Performance wise the selector might be a little slower, but in practice this is (almost) never a problem.

**Comment by gmetais** [comment]
Closed by #175.

**Comment by macbre** [comment]
Backported in analyze-css - https://github.com/macbre/analyze-css/pull/134
