### ISSUE TITLE
Redundant tags selectors - explanation and check

### ISSUE THREAD

**Issue by lucasgehin** [gmetais/YellowLabTools#162]
Hi,

I think you did a mistake with the check of redundant tags selectors.
It's said
> when "ul li" is specified in a rule, "ul" can be removed because the "li" element is always inside a "ul"

but it can also be **ol li** ...

Regards,

**Comment by gmetais** [comment]
Oh yes right, thank you! I'll change the description.

**Comment by gmetais** [comment]
Will be in the next release: https://github.com/gmetais/YellowLabTools/commit/07028ad3cd1c7f753feceded7c5cfd29c031fd75
