### ISSUE TITLE
Error 254: page loading failed in PhantomJS

### ISSUE THREAD

**Issue by ousamabenyounes** [gmetais/YellowLabTools#164]
Hi Gael, 
I just get a phantomJs error.
The link of my test: http://yellowlab.tools/queue/efgy0fseji
I've allready seen this error in the past, but now be sure i'll send you a report to help fixing issues.

Tested url: http://www.ooshop.com/courses-en-ligne/Home.aspx

**Comment by gmetais** [comment]
Hi @ousamabenyounes, thank you for reporting the issue!

I made an unique thread for all 254 errors here: #169. I've already reported your error inside :)
