### ISSUE TITLE
Error 1001: JavaScript profiling failed

### ISSUE THREAD

**Issue by ousamabenyounes** [gmetais/YellowLabTools#166]
Here is the link:
http://yellowlab.tools/queue/efj1adpnam

**Comment by gmetais** [comment]
I need the webpage url too :) The server doesn't keep any traces of failed tests.

**Comment by ousamabenyounes** [comment]
The website url for this failed test was: http://www.consoanimo.com/ wich is owned by wamiz.com startup

**Comment by gmetais** [comment]
Closed for #170. Thank you!
