### ISSUE TITLE
The 1Mb test fails

### ISSUE THREAD

**Issue by gmetais** [gmetais/YellowLabTools#171]
[This website](http://1mb.website/) should be exactly 1048576 bytes. YLT finds 1048175 bytes.
The missing 401 bytes are related to an empty JS file. It's empty but its headers represent 401 bytes.

This empty file is being ignored by YLT when calculating the total weight.

It's also not in the "small requests" count. In fact, there should even be an "empty file" rule to detect this kind of files.

Thank you @ronancremin!

**Comment by ronancremin** [comment]
You're welcome, this is exactly what it was made for (we found a bug in our own tool too).

**Comment by gmetais** [comment]
Hi @ronancremin,

I'm working on this issue. I'm now correctly including the empty file.

I've noticed that you changed the weight to 1,000,000 bytes. However I'm now finding 999,920 bytes and 80 bytes are still missing. Do you have a kind of weights list I could compare with mine?

``` json
{
  "totalWeight": 999920,
  "byType": {
    "html": {
      "totalWeight": 3503,
      "requests": [
        {
          "url": "http://1mb.website/",
          "weight": 3503
        }
      ]
    },
    "css": {
      "totalWeight": 6763,
      "requests": [
        {
          "url": "http://1mb.website/css/main.css",
          "weight": 595
        },
        {
          "url": "http://1mb.website/css/pure-min.css",
          "weight": 4383
        },
        {
          "url": "http://1mb.website/css/grids-responsive-min.css",
          "weight": 1785
        }
      ]
    },
    "js": {
      "totalWeight": 41890,
      "requests": [
        {
          "url": "http://1mb.website/js/vendor/modernizr-2.8.3.min.js",
          "weight": 6641
        },
        {
          "url": "http://1mb.website/js/plugins.js",
          "weight": 715
        },
        {
          "url": "http://1mb.website/js/main.js",
          "weight": 321
        },
        {
          "url": "http://1mb.website/js/jquery-1.12.0.min.js",
          "weight": 34213
        }
      ]
    },
    "json": {
      "totalWeight": 0,
      "requests": []
    },
    "image": {
      "totalWeight": 947764,
      "requests": [
        {
          "url": "http://1mb.website/img/1mb_logo.svg",
          "weight": 19144
        },
        {
          "url": "http://1mb.website/img/1kg_weight.jpg",
          "weight": 96168
        },
        {
          "url": "http://1mb.website/img/balance_scale.jpg",
          "weight": 121785
        },
        {
          "url": "http://1mb.website/img/prototype_kilogram.jpg",
          "weight": 96652
        },
        {
          "url": "http://1mb.website/img/background_image.jpg",
          "weight": 164804
        },
        {
          "url": "http://1mb.website/img/reference_weights.jpg",
          "weight": 131167
        },
        {
          "url": "http://1mb.website/img/weighing_of_the_heart.jpg",
          "weight": 133874
        },
        {
          "url": "http://1mb.website/img/silicon_sphere_for_Avogadro_project.jpg",
          "weight": 184170
        }
      ]
    }
  }
}
```

**Comment by gmetais** [comment]
Partially fixed by #180.

**Comment by ronancremin** [comment]
Hi Gaël,

I usually keep the reference file size available here: http://1mb.website/reference.txt

I'm pretty sure they are all correct—curl is my source of truth for all of this testing. 

Yes, as you've noticed I change the weight to 1,000,000 bytes after [a discussion with jubileu123](https://mobiforge.com/design-development/a-page-weight-reference-for-the-web). I think that he made valid points.

Ronan

**Comment by gmetais** [comment]
I found the problem: YLT was sending requests with the header `Connection: close`, so the server was responding with the header `Connection: close` too, instead of `Connection: keep-alive`. This is a difference of 5 bytes per request. 5*16 = 80.

It's fixed, and YLT might even become faster by recycling connections!

**Comment by ronancremin** [comment]
Nice! Good to know my math was correct.
