### ISSUE TITLE
www.sigmaaldrich.com/united-states.html fails with error: Error 254: page loading failed in PhantomJS

### ISSUE THREAD

**Issue by plermant** [gmetais/YellowLabTools#185]
Fails both from UI and with API.

**Comment by gmetais** [comment]
The page makes a double redirection.

Take a look here: https://www.webpagetest.org/result/160813_HH_c02feda7143ecd0f40874b9c622d8547/1/details/
Requests number 35 and 54.

Sorry I can't help you further, this is a limitation in https://github.com/macbre/phantomas. Not sure it's easy to fix, but you might want to open an issue there.

**Comment by plermant** [comment]
Hi Gael -


Thank you for looking into it.


The requests 35 and 54 you indicate seem to be 304s, and not redirects (301/302). Are you saying that Phantomas can't support 304s?


Merci

Pierre


________________________________

**Comment by gmetais** [comment]
Sorry I forgot to say they are **JavaScript** redirections. Then the response is a 304 because the file didn't change.
