### ISSUE TITLE
Installation fail  because of  lwip@0.0.9 error.

### ISSUE THREAD

**Issue by ghost** [gmetais/YellowLabTools#187]
OS: Windows 7 64bits
Node Ver: 6.2.2
npm ver: 3.9.5

When I try to install/build YLT it fails because of:

> npm ERR! lwip@0.0.9 install: node-gyp rebuild
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the lwip@0.0.9 install script 'node-gyp rebuild'.

Tried to install only lwip package but it fails with the same error. 
I checked for something similar in lwip repo and turned out there is such kind of an issue.
[https://github.com/EyalAr/lwip](url)

After more verbose and detailed observation there is this error: 

> "...\node_modules\lwip\build\lwip_decoder.vcxproj" (default target) (2) ->
> (Desktop_PlatformPrepareForBuild target) ->
>   C:\Program Files x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: **The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution"**. [..\node_modules\lwip\build\lwip_decoder.vcxproj]

The supported  version of the OS for this SDK are Win 8.1 , Win 10 , Win 2012. I get error when I try to install it under Win 7. Investigating the log but nothing so far. I'm using company laptop but in general we have admin rights. Still not sure if permission problem or platform one.

Anyone had the same issue?

**Comment by gmetais** [comment]
This is a problem with your cpp compiler. The `lwip` module used by YellowLabTools has C++ components that require a compilation on installation. That's all I can tell.

**Solution 1:** Ask on https://github.com/EyalAr/lwip for more help

**Solution 2:** Install a virtual machine on your computer. If you want to install faster, I provide a Vagrant config: https://github.com/gmetais/YellowLabTools/wiki/Install-your-private-server#method-2-in-a-virtual-machine-with-vagrant

**Comment by camlafit** [comment]
Hi

With vagrant config, it's bug also :/

**Comment by camlafit** [comment]
Hi

I prepare a patch to use Vagrant version. We must use at lest last ubuntu LTS, then compilation can be done.
Install at least Node 4 looks required , as explained on [wiki/Install-your-private-server](../wiki/Install-your-private-server)

**Comment by gmetais** [comment]
Hi @camlafit,

I would love a pull request :)

**Comment by gmetais** [comment]
Fixed by #251.
