### ISSUE TITLE
Install successfully however test any url got bad argument error

### ISSUE THREAD

**Issue by lizicuenca** [gmetais/YellowLabTools#188]
I was able to successfully install the tool however for every url I put in, i got bad argument error. I am really like the features in the tool however i am stuck now.  Any help or direction would be appreciated. 

While the error looks like related to phantonjs however I would like check here see if anyone run into similar error. 

I created a fresh aws instance today and the only thing i installed are listed below: 
Server : ubuntu
node -v : v6.4.0
npm -v : 3.10.3
AWS image standard ubuntu version: ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-20160714 (ami-d732f0b7)

The error i ran into is: 
ubuntu@ip:~/YellowLabTools$ node bin/cli.js http://www.google.com
internal/child_process.js:278
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:278:26)
    at exports.spawn (child_process.js:380:9)
    at engines.run (/home/ubuntu/YellowLabTools/node_modules/phantomas/lib/engines.js:127:10)
    at phantomas (/home/ubuntu/YellowLabTools/node_modules/phantomas/lib/index.js:66:16)
    at /home/ubuntu/YellowLabTools/lib/tools/phantomas/phantomasWrapper.js:125:27
    at /home/ubuntu/YellowLabTools/node_modules/async/lib/async.js:651:21
    at /home/ubuntu/YellowLabTools/node_modules/async/lib/async.js:718:13
    at iterate (/home/ubuntu/YellowLabTools/node_modules/async/lib/async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (/home/ubuntu/YellowLabTools/node_modules/async/lib/async.js:281:9)

For further detail, please refer to this thread: 
https://github.com/macbre/phantomas/issues/598

**Comment by gmetais** [comment]
Hi!

Could you try this in your Yellow Lab Tools directory?
```
DEBUG=phantomas:engines ./node_modules/phantomas/examples/promise.js
```

**Comment by lizicuenca** [comment]
Hi Gmetais, I don't know how to use your code above. Do you just mean run this line in shell command? I actually get my the issue fixed and got YellowLabTools up and run now! 

Since i see logs related to lwip and phantomjs, i start to clear those packages and check each site for reinstall. 

```
# reinstall phantomjs
sudo npm install -g phantomjs
sudo npm -g install phantomjs-prebuilt
sudo npm -g install phantomas

# rebuild lwip 
rm .node-gyp (from my home directory) 
sudo apt-get install -y build-essential

# remove node_modules from YellowLabTools 
rm -r ./YellowLabTools/node_modules

# reinstall everything
cd YellowLabTools
npm install

```

After above, my server is up. i am now running into error 252. I suspect that error is from phantomjs and decided to test it in isolation. 
run phantomjs only and got an error like below: 
`/usr/lib/node_modules/uncss/node_modules/phridge/node_modules/phantomjs/lib/phantom/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory`

resolved above issue using: 

`sudo apt-get install libfontconfig`

At this time, the application is running and report my the test result in page. 

 I am ready to my next step of learning the features of the tools now. Thank you team for creating this cool production.

Please excuse me for my limited experience with node and javascript. Just start to learn them a month ago. Please let me know if stay something wrong.

**Comment by gmetais** [comment]
I'm glad you made it!

I'm adding `libfontconfig` to the wiki page.
