### ISSUE TITLE
How to trending of selected metrics for a given urls

### ISSUE THREAD

**Issue by lizicuenca** [gmetais/YellowLabTools#190]
Newbie question: I love the tools and metrics and I would like to make this tool part of development process. Here are two cases that I have: 
1. during the development, for same url, compare key metrics change over the time. 
2. after code in production, run list of urls and report on top offender on key performance metrics. 

Do you know if this something already build in or I may need to use different tool? Any help would be appreciated.

**Comment by gmetais** [comment]
Hi @lizicuenca,

As far as I know there is no tool that does exactly what you are looking for. There is a grunt module that can be used (even if you're not using grunt in your project) to check some urls and automatically check the scores against some thresholds you set: https://github.com/gmetais/grunt-yellowlabtools

**Comment by lizicuenca** [comment]
Thank you for reply. Grunt is new to me. I will check them out.
