### ISSUE TITLE
Missing requirement for CLI/Node installation on Windows

### ISSUE THREAD

**Issue by hidanielle** [gmetais/YellowLabTools#194]
I spent longer than I should have trying to troublehsoot why I couldn't get the installation to work on Windows. Found it was lwip causing the problem and that following the instructions [here ](https://github.com/nodejs/node-gyp#installation) solved my issue. I suggest adding this to the YLT documentation, or atleast Python added as a dependency.

**Comment by gmetais** [comment]
Hi Danielle,

Sorry for the time you spent and thank you for spending a little more time writing here. I added your link to the documentation: https://github.com/gmetais/YellowLabTools/wiki/Install-your-private-server#method-1-manual-installation

Is it working ok now, except the error you get on google.fr (https://github.com/gmetais/YellowLabTools/issues/150)?

**Comment by hidanielle** [comment]
Awesome! Yes, I was able to get the install working after that.
