### ISSUE TITLE
No screenshots with cookied domains

### ISSUE THREAD

**Issue by bobstrecansky** [gmetais/YellowLabTools#195]
I'm attempting to use yellowlab.tools for a website that uses cookie auth.  I've added all the cookie information into the cookie form field, but the page doesn't render in yellowlab.tools.  Is this a known issue?  Signing up for a free Mailchimp account (https://login.mailchimp.com/signup) and using that cookie to attempt to sign in is where yellowlab.tools fails.

**Comment by gmetais** [comment]
Hi @bobstrecansky,

YLT is only able to set **one cookie**. I've been trying to find which one was the session cookie on mailchimp but I couldn't. Do you know the name of the cookie?

If it needs several cookies, then we are stuck. Maybe it is worth working on a solution where YLT could handle more than one cookie.

**Comment by bobstrecansky** [comment]
Gaël,

Yes, that is the issue. We have a couple session cookies that we need to set. Other similar tools that I've used will semicolon delineate the cookies. Is that something that could be added?

**Comment by bobstrecansky** [comment]
@gmetais - just wanted to follow up.  I can take a stab at trying to allow multiple cookies, but you know the codebase much better than I.

**Comment by gmetais** [comment]
We are limited here by the Phantomas API (https://github.com/macbre/phantomas), that only accepts 1 cookie, or the path to a "cookie jar" file.

Solution 1: create a temporary cookie jar file for tests with cookies, and delete it at the end of the test.

Solution 2: it looks like the Phantomas API could be enhanced to accept several cookies. I prefer this way as I find it cleaner, but I don't have time to write a pull request. Do you want to have a look?

**Comment by bobstrecansky** [comment]
@gmetais - looks like @macbre is working on this for release 1.8:
https://github.com/macbre/phantomas/issues/667

You'd be able to add support for multiple cookies after that?

**Comment by gmetais** [comment]
Cool! Yes I will.

**Comment by eplle** [comment]
Hi!

I´m also interested in sending multiple cookies, any news on this?
@gmetais you mentioned that one solution would be to create a cookie jar file. Could you elaborate on how to create one (what format?) and how to pass it to ylt?

Many thx!

**Comment by gmetais** [comment]
Sorry, it's currently not possible to send a jar file to YLT.

**Comment by eplle** [comment]
I´m able to set multiple cookies in phantomas using --config, would it be possible to add support for a config file in YLT?

**Comment by gmetais** [comment]
Good idea, I'll add this option to the CLI when I have some time.

**Comment by macbre** [comment]
@gmetais: resolved on phantomas side by https://github.com/macbre/phantomas/pull/680

**Comment by gmetais** [comment]
Fixed by #216 (Phantomas 1.18 adds support for multiple cookies).

Thank you @macbre for the christmas gift :)
