### ISSUE TITLE
Couldn't profile Amazon  - Javascript profiling failed

### ISSUE THREAD

**Issue by lightningtommo** [gmetais/YellowLabTools#196]
http://yellowlab.tools/queue/ej34usaoy3

Tested URL: http://www.amazon.co.uk
Test failed
Error 1001: JavaScript profiling failed

**Comment by gmetais** [comment]
Hi, and thanks for reporting this issue!

Could you please add it to this thread: https://github.com/gmetais/YellowLabTools/issues/170 ?

**Comment by gmetais** [comment]
Fixed by #196, thanks to your bug report. Thanks!
