### ISSUE TITLE
Process fails with ECONNRESET

### ISSUE THREAD

**Issue by a3020** [gmetais/YellowLabTools#198]
I'm running an instance of YLT on Debian and created a service to keep it running. Sometimes an API request fails and **crashes the process**. I'm not too familiar with nodejs. Any idea what might cause the crash below? 

```
Oct 16 15:40:13 debian server-node.js[26012]: events.js:141
Oct 16 15:40:13 debian server-node.js[26012]: throw er; // Unhandled 'error' event
Oct 16 15:40:13 debian server-node.js[26012]: ^
Oct 16 15:40:13 debian server-node.js[26012]: Error: read ECONNRESET
Oct 16 15:40:13 debian server-node.js[26012]: at exports._errnoException (util.js:907:11)
Oct 16 15:40:13 debian server-node.js[26012]: at Pipe.onread (net.js:557:26)
Oct 16 15:40:13 debian systemd[1]: yellowlabtools.service: main process exited, code=exited, status=1/FAILURE
Oct 16 15:40:13 debian systemd[1]: Unit yellowlabtools.service entered failed state.
```

A script that consumes the API returns `cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`.

**Comment by gmetais** [comment]
Hello,

This is a problem I experimented when implementing [grunt-yellowlabtools](https://github.com/gmetais/grunt-yellowlabtools). It is caused by a timeout, but I don't know which party times out.

I had to implement a polling to fix this: https://github.com/gmetais/grunt-yellowlabtools/commit/ab21b11343b4f993c4d5bace81e9a033fe946af0

There might be some other ways to fix this, but I could not find a proper one.

**Comment by gmetais** [comment]
Have a look here for the polling method: https://github.com/gmetais/YellowLabTools/wiki/Public-API#waitforresponse-boolean

**Comment by a3020** [comment]
@gmetais thanks for the links. Do I understand it correctly that we can't rely on the `waitForResponse: false` mode therefore?

I've tested with Postman, a REST client, as well. With Postman I didn't get an error. Do you have any thoughts on that? I'm using `Content-Type: application/x-www-form-urlencoded` as a request header.

**Comment by gmetais** [comment]
You can't rely on waitForResponse: **true**. 

The timeout with depends on the duration of the test. If the test goes in the queue and waits behind other tests, that can be several minutes of waiting.

Usually, when Node throws an ECONNRESET, it means the **other** party hung up the connection. But your curl error looks like curl neither did hang up the connection. Could the problem be between Node and curl, at the OS level?

Do you confirm that this problem crashes the YLT server? I can fix that.

By the way, what's the language of your script?

**Comment by gmetais** [comment]
I tried to reproduce the bug with cURL but I can't...

Could you give your cURL syntax?
I'm using this one:
```curl -H "Content-Type: application/json" -X POST -d '{ "url": "http://www.lemonde.fr", "waitForResponse": true, "screenshot": true, "device": "tablet" }' http://localhost:8383/api/runs```
As you see, I'm using the `application/json` content type, not the `application/x-www-form-urlencoded`.

By the way, what version of NodeJs do you use?

**Comment by a3020** [comment]
@gmetais I removed the source directory, reinstalled everything and made sure nothing was listening on port 8383 (`lsof -i :8383`). Then I flushed my firewall rules and tried again. Seems the issue has been resolved. I'm not getting any errors so far. 🎉
