### ISSUE TITLE
Error with SVGs as data URIs in the CSS

### ISSUE THREAD

**Issue by oilvier** [gmetais/YellowLabTools#201]
Hi,

I keep getting an error in the "CSS syntax error" category regarding SVG used as data URIs and URL encoded.

Error: `%3Csvg%20version%3D%221.1%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220 0 12 12%22%20preserveAspectRatio%3D%22none%22%3E%0A%09%3Cpath%20fill%3D%22rgba(255,255,255,.99)%22%20d%3D%22M7.1,6l4.8-4.8C12,1,12,.9,11.9,.8l-0.7-0.7C11.2,0,11.1,0,11,0s-0.1,0-0.2,.1L6,4.9L1.1,.1 C1,0,.9,0,.8,.1L0.1,.8C0,.9,0,1,.1,1.1L4.9,6l-4.8,4.8c-0.1,.1-0.1,.3,0,.4l0.7,.7c0,0,.1,.1,.2,.1s0.1,0,.2-0.1 L6,7.1l4.8,4.8c0.1,0,.1,.1,.2,.1s0.1,0,.2-0.1l0.7-0.7c0.1-0.1,.1-0.3,0-0.4L7.1,6z%22%20%2F%3E%0A%3C%2Fsvg%3E");background-position:center center;}.ui-dialog-titlebar-close:hover` is an invalid expression

The code seems OK to me.

**Comment by gmetais** [comment]
Hi @oilvier,

Do you have a bigger extract, with the entire CSS rule please?

**Comment by oilvier** [comment]
Yes, sure : 

```
.ui-dialog-titlebar-close{padding:.6em;width:1em;height:1em;cursor:pointer;font-size:25px;font-size:1.5625rem;text-align:center;background-color:#09456e;background-image:url("data:image/svg+xml;charset=utf8,%3Csvg%20version%3D%221.1%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220 0 12 12%22%20preserveAspectRatio%3D%22none%22%3E%0A%09%3Cpath%20fill%3D%22rgba(255,255,255,.99)%22%20d%3D%22M7.1,6l4.8-4.8C12,1,12,.9,11.9,.8l-0.7-0.7C11.2,0,11.1,0,11,0s-0.1,0-0.2,.1L6,4.9L1.1,.1 C1,0,.9,0,.8,.1L0.1,.8C0,.9,0,1,.1,1.1L4.9,6l-4.8,4.8c-0.1,.1-0.1,.3,0,.4l0.7,.7c0,0,.1,.1,.2,.1s0.1,0,.2-0.1 L6,7.1l4.8,4.8c0.1,0,.1,.1,.2,.1s0.1,0,.2-0.1l0.7-0.7c0.1-0.1,.1-0.3,0-0.4L7.1,6z%22%20%2F%3E%0A%3C%2Fsvg%3E");background-repeat:no-repeat;-webkit-background-size:60% 60%;background-size:60% 60%;background-position:center center;text-indent:-9999em}.ui-dialog-titlebar-close:hover,.ui-dialog-titlebar-close:focus,.ui-dialog-titlebar-close:active,.ui-dialog-titlebar-close:visited{background-color:#073656}
```

I also put the following rule that seems to be mixed with the previous one in the error report.

**Comment by gmetais** [comment]
I'm trying to reproduce with this extract as a CSS file but it works with no error. Usually YLT (and the [analyze-css](https://github.com/macbre/analyze-css/) module) works correctly with SVGs.

Maybe the error comes from some kind of side effect with previous parts of the CSS file. Do you have the same issue when using [analyze-css](https://github.com/macbre/analyze-css/) directly?

Or an encoding problem. What's the encoding of the CSS file, specified by the server in the HTTP headers?

**Comment by oilvier** [comment]
I've just tried with analyze-css and I think I've narrowed the problem down : 

It seems to occur when there's more than one call to an SVG in an inlined CSS with code after the last SVG déclaration.

* 2 SVG calls, inlined CSS and code after the last SVG declaration-> **it doesn't work**
```
.foo{background-image:url("data:image/svg+xml;charset=utf8,%3Csvg%20version%3D%221.1%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220 0 13 9%22%20preserveAspectRatio%3D%22none%22%3E%0A%09%3Cpath%20fill%3D%22rgba(5,178,189,.99)%22%20d%3D%22M8.53 0L7.19 1.352l2.18 2.193H0v1.912h9.37L7.19 7.65l1.34 1.352 4.47-4.5z%22%20%2F%3E%0A%3C%2Fsvg%3E")}.bar{background-image:url("data:image/svg+xml;charset=utf8,%3Csvg%20version%3D%221.1%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220 0 25 21%22%20preserveAspectRatio%3D%22none%22%3E%0A%09%3Cpath%20fill%3D%22rgba(5,46,73,.99)%22%20d%3D%22M7.5,15.6l-4.8-4.9L0,13.4l6.4,6.5l0,0L7.5,21l18-18.3L22.8,0L7.5,15.6z%22%20%2F%3E%0A%3C%2Fsvg%3E")}.baz{}
```

* Same as before, but with a new line between the 2 SVG calls -> **it works**
```
.foo{background-image:url("data:image/svg+xml;charset=utf8,%3Csvg%20version%3D%221.1%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220 0 13 9%22%20preserveAspectRatio%3D%22none%22%3E%0A%09%3Cpath%20fill%3D%22rgba(5,178,189,.99)%22%20d%3D%22M8.53 0L7.19 1.352l2.18 2.193H0v1.912h9.37L7.19 7.65l1.34 1.352 4.47-4.5z%22%20%2F%3E%0A%3C%2Fsvg%3E")}
.bar{background-image:url("data:image/svg+xml;charset=utf8,%3Csvg%20version%3D%221.1%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220 0 25 21%22%20preserveAspectRatio%3D%22none%22%3E%0A%09%3Cpath%20fill%3D%22rgba(5,46,73,.99)%22%20d%3D%22M7.5,15.6l-4.8-4.9L0,13.4l6.4,6.5l0,0L7.5,21l18-18.3L22.8,0L7.5,15.6z%22%20%2F%3E%0A%3C%2Fsvg%3E")}.baz{}
```

* 2 SVG calls, but no code at the end -> **it works**
```
.foo{background-image:url("data:image/svg+xml;charset=utf8,%3Csvg%20version%3D%221.1%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220 0 13 9%22%20preserveAspectRatio%3D%22none%22%3E%0A%09%3Cpath%20fill%3D%22rgba(5,178,189,.99)%22%20d%3D%22M8.53 0L7.19 1.352l2.18 2.193H0v1.912h9.37L7.19 7.65l1.34 1.352 4.47-4.5z%22%20%2F%3E%0A%3C%2Fsvg%3E")}.bar{background-image:url("data:image/svg+xml;charset=utf8,%3Csvg%20version%3D%221.1%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220 0 25 21%22%20preserveAspectRatio%3D%22none%22%3E%0A%09%3Cpath%20fill%3D%22rgba(5,46,73,.99)%22%20d%3D%22M7.5,15.6l-4.8-4.9L0,13.4l6.4,6.5l0,0L7.5,21l18-18.3L22.8,0L7.5,15.6z%22%20%2F%3E%0A%3C%2Fsvg%3E")}
```

* 1 SVG call -> **it works**
```
.foo{background-image:url("data:image/svg+xml;charset=utf8,%3Csvg%20version%3D%221.1%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220 0 13 9%22%20preserveAspectRatio%3D%22none%22%3E%0A%09%3Cpath%20fill%3D%22rgba(5,178,189,.99)%22%20d%3D%22M8.53 0L7.19 1.352l2.18 2.193H0v1.912h9.37L7.19 7.65l1.34 1.352 4.47-4.5z%22%20%2F%3E%0A%3C%2Fsvg%3E")}.bar{}
```

**Comment by gmetais** [comment]
Thanks a lot for your investigation. Now we know it's a problem in analyze-css. But this tool relies on another npm package: https://www.npmjs.com/package/css

It would really cool if you could run your exemples of code directly with a minimal node script requiring this package and open an issue directly in their repository. I'm far from my computer today!

**Comment by oilvier** [comment]
Thanks for your help !

It's getting a bit too technical for me, but I can at least reproduce the error with their online GUI (http://iamdustan.com/reworkcss_ast_explorer/).

I'll try and post an issue on their repo and keep you posted.

**Comment by oilvier** [comment]
Well in fact there's already an issue for that (https://github.com/reworkcss/css/issues/67). Unfortunately no answer since 2015 😞

**Comment by gmetais** [comment]
Yes, it looks like there's not much change on the repo. Many pending pull requests too, so we can't even try to fix it ourself...

**Comment by oilvier** [comment]
Do I close the issue here, since you're not responsible for this ?

**Comment by gmetais** [comment]
Yes, let's close.
