### ISSUE TITLE
Get a error 255

### ISSUE THREAD

**Issue by isamedia** [gmetais/YellowLabTools#202]
The Error:
Error 255: Phantomas error

Webpage URL: https://www.1und1.de/
Tested device: desktop
Makes a redirection: No
Other information that could help debugging: this website loads a huge amount of JS (522 kilobytes)

Then i run yellowlabs as local service I dont get the error, but I get all pounts as grenn and ok. But I know, by this domain nothing is ok.

**Comment by gmetais** [comment]
Thanks for the report. For the moment I have no idea how to fix this bug...
I reposted your issue in #168 and I'm closing this one.
