### ISSUE TITLE
Generate dashboard html from json result?

### ISSUE THREAD

**Issue by eplle** [gmetais/YellowLabTools#203]
Hi!

Is it possible to generate a html result page using node?
I currently have a json result from phantomas but would like to have the nice visualization support by the online tool.

(perhaps mark this as a question)

**Comment by gmetais** [comment]
Hi,

Sorry it's not possible. Although YLT is based on Phantomas, it does a lot of other things that are not in Phantomas before generating the report. Also, the result page is built with Angular, so it's not actually building a real HTML file.

**Comment by eplle** [comment]
Okay, thank you!
