### ISSUE TITLE
Souci lors d'un test

### ISSUE THREAD

**Issue by Ratanas** [gmetais/YellowLabTools#205]
Bonjour,

Tested url:   http://www.co-chu-rouen.fr
Test failed

Error 254: page loading failed in PhantomJS

**Comment by gmetais** [comment]
Hi,
For a reason I don't understand, your page is automatically refreshed once it's loaded. It can be noticed on the browser or in WebPageTest (request 45 : https://www.webpagetest.org/result/161209_3S_8XS/1/details/#waterfall_view_step1).
Phantomas is not able to handle a page that's redirected with JS. Try to understand why your page is refreshed and fix it.

(Pour une raison que je ne parviens pas à comprendre, ta page est automatiquement rafraîchie une fois qu'elle a fini de charger. Cela se voit dans le navigateur, ou bien dans WebPageTest à la requête numéro 45 : https://www.webpagetest.org/result/161209_3S_8XS/1/details/#waterfall_view_step1
Phantomas n'est pas capable de gérer une page qui se rafraîchit en JS. Essaye de comprendre pourquoi ta page se rafraîchit et répare la.)
