### ISSUE TITLE
Autofill URL input field

### ISSUE THREAD

**Issue by sanderheilbron** [gmetais/YellowLabTools#206]
When the URL input field can get its value from a URL parameter (i.e. http://yellowlab.tools/?url=https:%2F%2Fwww.google.com), YellowLabTools can be opened with a pre-populated input field by using a bookmarklet or browser extension from the web page which needs to be tested.

Tools like Google PageSpeed Insights and WebPageTest offer pre-populated form fields. It would be very helpful when YellowLabTools also offers this feature.

**Comment by gmetais** [comment]
Should it automatically start the test, or just populate the url field?

**Comment by sanderheilbron** [comment]
That would be a very nice addition!

**Comment by gmetais** [comment]
Will be shipped in v1.12.
Documentation is already ready here: https://github.com/gmetais/YellowLabTools/wiki/Use-from-a-bookmarklet
