### ISSUE TITLE
Below the fold images.

### ISSUE THREAD

**Issue by schorsch3000** [gmetais/YellowLabTools#207]
Hi,
i'm a little bit stuck at the Below the fold images Rating.
I use a lazyloader, in fact it's the recommended.
I use it with an offset so the Images are loaded BEFORE they reach the viewport.
Lazyloading is fine, but there is no need to annoy the user with that laziness.
I really like the images to appear JUST BEFORE they reach the viewport.

That gives a bad rating.

Is that a bad thing to do?

**Comment by gmetais** [comment]
There is no right answer about the best lazyloading offset. Some think it's 0px, some think it's 500px. Do what you think is best for your users.

But I agree YLT could be a bit little less strict about this. I think I'll add a 100px offset in a future release.

**Comment by schorsch3000** [comment]
That sounds good.
btw. what is the below the fold height for desktop?
I use an 1080 screen, having chrome, with system window decoration, and bookmark-bar, leaving me with a viewport at 965px height.
I see most of the images below the fold :)

**Comment by gmetais** [comment]
The default viewport is 1280x1024 for desktop.

**Comment by gmetais** [comment]
I corrected the above, it's 1366x768.

**Comment by gmetais** [comment]
I just added an offset of 100px in the test (will be available in v1.12).

**Comment by schorsch3000** [comment]
Nice, thanks :+1:
