### ISSUE TITLE
jQuery usage

### ISSUE THREAD

**Issue by schorsch3000** [gmetais/YellowLabTools#208]
Im stuck with the jQuery usage score.
I don't use jQuery alot on load.
Sure i could get rid of jQuery for the few onload calls.
I use Jquery alot on userinteraction.
is it really a bad thing to have only jquery instead of jquery and some selfmade scripts?

**Comment by gmetais** [comment]
If your question is "Should I add more JS code on load so that jQuery is more and YLT gives me a better score", the answer is no.

**Comment by schorsch3000** [comment]
But what does the score on jQuery usage is good for then?
The ony thing to get "better" at this score i can imagin is to make things worse, the one or the other way :)

**Comment by gmetais** [comment]
This rule will be removed in YLT v1.12.
