### ISSUE TITLE
Repeatedly getting Error 255 Phantomas error

### ISSUE THREAD

**Issue by marston-gould-apfm** [gmetais/YellowLabTools#222]
Doesn't really matter what page I submit.
We are running an enterprise website, so I am suspecting that either the IP is blocked on your end or ours.
I have not submitted > 50 URLs
What IP does YellowLabs used to scan pages?

**Comment by marston-gould-apfm** [comment]
Webpage URL: http://www.aplaceformom.com/senior-apartments/california/los-angeles
Tested device: desktop
Makes a redirection: no

This page is very streamlined, DOM is very small. 
Total page size is 783KB with 30 requests to complete DOM
Page fully loads in 2.8 sec
TTFB is 0.289 sec

On reload, TTFB is only 0.171sec and DOM completes with 11 requests in 2.042 sec.

**Comment by rockeynebhwani** [comment]
I am also getting same error on URL - http://direct.asda.com/george/womens/lingerie/lingerie-sets/entice-lace-trim-balcony-bra-brazilian-knickers/SET2313,default,pd.html

Here is the link to results page where this error can be seen - http://yellowlab.tools/queue/epaux2wvs9

**Comment by rockeynebhwani** [comment]
Looks like this is duplicate  of https://github.com/gmetais/YellowLabTools/issues/168

**Comment by gmetais** [comment]
Closing a duplicate (#168).
