### ISSUE TITLE
Engine "webkit" not found!

### ISSUE THREAD

**Issue by sanidhay** [gmetais/YellowLabTools#223]
Hi,
I am getting below error after launching test.
I followed all the steps mentioned in documentation.

Any help please.

Test failed

Engine "webkit" not found!

**Comment by gmetais** [comment]
Hi!
It looks like the `npm install` failed to install PhantomJS.
You can try to install PhantomJS globally (`npm install phantomjs -g`) and it should work.

**Comment by sanidhay** [comment]
Thanks. I will give it a try again.

**Comment by gmetais** [comment]
Hi @sanidhay, is it working now?
