### ISSUE TITLE
Webfont Analysis Bugged 

### ISSUE THREAD

**Issue by fibigerg** [gmetais/YellowLabTools#224]
Hi, Yellow Lab loads all available character subsets. The result is a low score for all sites that use Google Fonts. It affects multiple sections:
- Total weight 
- Number of requests
- Webfonts number
- Unused Unicode Ranges

Yellow Lab results are not relevant at the moment because of this issue.

E.g. this test http://yellowlab.tools/result/enzr9f2qfw

Do you have any ideas how to handle the issue? As far as I know modern browsers load only unicode ranges they are rendering.

**Comment by marston-gould-apfm** [comment]
http://mandrillapp.com/track/click/30344824/www.webpagetest.org?p=eyJzIjoiQTFCSmFmY1BlcmRYR3dPem11Z28zZ3NYcnpzIiwidiI6MSwicCI6IntcInVcIjozMDM0NDgyNCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3d3dy53ZWJwYWdldGVzdC5vcmdcXFwvcmVzdWx0XFxcLzE3MDMxNF9TMV8xQlNGXFxcLzNcXFwvZGV0YWlsc1xcXC8jd2F0ZXJmYWxsX3ZpZXdfc3RlcDFcIixcImlkXCI6XCI3NGFhNjhiYzA1YzY0OTc4YmIxMGE2ODU2Y2YzNWM2NVwiLFwidXJsX2lkc1wiOltcIjIyZjZlZGUzYjRmOGUzM2VkZGM3YjQzYWQyYzA2NWUzOWU1MjkwZjNcIl19In0

It does appear that your fonts take a long time to load.

One of the tricks we are working on (we have similar issue) is we are going to upload our fonts into Font Squirrel
Delete the glyphs we don’t use and combine all the fonts into a single font file.

**Comment by gmetais** [comment]
Sorry for the delay. This is a real problem!

> Do you have any ideas how to handle the issue? As far as I know modern browsers load only unicode ranges they are rendering.

You are right, browsers wait until a subset is needed before loading it. I wish a new version of PhantomJS could fix the problem. There is a work in progress about this but it's hard to tell if it's going to fix this specific problem.

There is another fix I'm thinking about, by removing webfonts from the list if it looks like none of its chars are used on the page.

**Comment by Jbz797** [comment]
Some news about this issue ?

**Comment by gmetais** [comment]
Kind of fixed by #234.
