### ISSUE TITLE
Manual installation error

### ISSUE THREAD

**Issue by Brian11f** [gmetais/YellowLabTools#225]
Hi, zumiez.com works on http://yellowlab.tools/ but in a local manual installation I get a 254 error for http://zumiez.com URL and the following if I use the full www.zumiez.com URL. I can confirm that the installation is working correctly as it run fine on google.com.

Launching test eo9qt2xjj0 on http://www.zumiez.com
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:801:14)

The installation is the latest version.

**Comment by gmetais** [comment]
Hi Brian!

You seem to experiment the same problem as #199. I hope we can find a solution.
Could you try my suggestion to reinstall as explained in the other issue?
Also can you tell me your OS name and NodeJs version number?

**Comment by Brian11f** [comment]
Thanks Gaël, I am on Sierra and v6.9.2. Sounds good, ill follow the instructions in #199.

**Comment by Brian11f** [comment]
Hi Gaël, I found that it was a peer dependency for grunt 4.0.0, 4.0.1 and jpegoptim module required brew install jpeg. Thanks, your tool is really awesome!
