### ISSUE TITLE
Style syntax validator does not appear to take "type" attribute into account

### ISSUE THREAD

**Issue by a701440** [gmetais/YellowLabTools#229]
``
<style type="junk">
 do not complain about this.
</style>
``

**Comment by gmetais** [comment]
Thanks for the bug report,
This doesn't seem to be used on many websites, but I've opened an issue here to fix it: https://github.com/macbre/phantomas/issues/694

**Comment by macbre** [comment]
phantomas v1.19.0 is out

**Comment by gmetais** [comment]
Thanks @macbre!

**Comment by gmetais** [comment]
Fixed by #233 (Phantomas upgraded to v1.19.0).
