### ISSUE TITLE
Location is not shown for duplicate css selectors 

### ISSUE THREAD

**Issue by a701440** [gmetais/YellowLabTools#230]
Would be nice to show the sheet and line number for each duplicate css selector.

**Comment by gmetais** [comment]
Hi and thank you for your suggestion.

This would require some changes on the Phantomas project. I've just opened an issue there: https://github.com/macbre/phantomas/issues/693

**Comment by macbre** [comment]
phantomas v1.19.0 is out

**Comment by gmetais** [comment]
You rule!

**Comment by gmetais** [comment]
Fixed by #233.
