### ISSUE TITLE
Bookmarklet for test the current url: issue with form submit

### ISSUE THREAD

**Issue by e-orlov** [gmetais/YellowLabTools#236]
Hi
First of all - really impressive tool!

I' trying to create a bookmarklet to test the url, where a user currently is, with yellowTools. The similar bookmarklet i've created for other sites, like Google Speed Insights Test and it worked like expected. Not so with YellowTools - i can't submit the form submit button from bookmarklet out. Now i have the following code:

1.
`javascript:(function(){ window.open('http://yellowlab.tools/?url='+encodeURIComponent(location.href));document.forms[this.form.id].submit()})();`

2.
`javascript:(function(){ window.open('http://yellowlab.tools/?url='+encodeURIComponent(location.href));document.getElementsByClass('launchBtn')[1].click()})();`

With both of them i achieve that http://yellowlab.tools opens, the url of the previous page is filled into the form, but the submit button remains not submitted and test doesn't start.

Could you point me to the correct test starting from bookmarklet out? And, surely, post the bookmarklet in the list of possible test methods ;)

**Comment by gmetais** [comment]
Hi @e-orlov,

You need to add the `&run=1` parameter to your URL and the form is automatically submitted. Doc is here: https://github.com/gmetais/YellowLabTools/wiki/Use-from-a-bookmarklet

See you :)
