### ISSUE TITLE
YellowLabTools output is empty

### ISSUE THREAD

**Issue by vcvetkovs** [gmetais/YellowLabTools#237]
Output is almost empty, it outputs only number
![image](https://user-images.githubusercontent.com/6433851/27769148-46a44c9a-5f2c-11e7-8c8d-7aa91eff8145.png)

Windows 10 64x, gyp installed, node version 7.3

**Comment by gmetais** [comment]
Hi vcvetkovs,

This is the same bug as #150. Sorry about it, I don't have any clue on how to fix it...
