### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by xiaowuming** [gmetais/YellowLabTools#238]
In file included from ../src/lib/png/png.c:14:0:
../src/lib/png/pngpriv.h:805:4: error: #error ZLIB_VERNUM != PNG_ZLIB_VERNUM "-I (include path) error: see the notes in pngpriv.h"
 #  error ZLIB_VERNUM != PNG_ZLIB_VERNUM \
    ^
lwip_decoder.target.mk:166: recipe for target 'Release/obj.target/lwip_decoder/src/lib/png/png.o' failed
make: *** [Release/obj.target/lwip_decoder/src/lib/png/png.o] Error 1
make: Leaving directory '/home/wip/YellowLabTools/node_modules/lwip/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-16-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/wip/YellowLabTools/node_modules/lwip
gyp ERR! node -v v8.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN grunt-blanket@0.0.10 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-express@1.4.1 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-inline-angular-templates@0.1.5 requires a peer of grunt@~0.4.1 but none was installed.
npm WARN grunt-line-remover@0.0.2 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-contrib-watch@0.6.1 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-parallel@0.3.1 requires a peer of grunt@~0.4.0 but none was installed.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lwip@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwip@0.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wip/.npm/_logs/2017-08-18T03_30_16_523Z-debug.log

**Comment by sergiozia** [comment]
I'm encountering also the same problem (node 8.5.0, npm 5.3.0)
When I downgrade nodeJS to the 7.5.0 release, lwip 0.0.9 builds without any error then the installation is ok and the YellowLabTools server runs

NB : pajk-lwip 0.2.0 builds without any error using nodeJS 8.5.0
