### ISSUE TITLE
YellowLabTools test failed Error 254: page loading failed in PhantomJS

### ISSUE THREAD

**Issue by bsandeepreddy** [gmetais/YellowLabTools#240]
![image](https://user-images.githubusercontent.com/13243847/30705483-92eec766-9ec3-11e7-97e9-a3f168256323.png)

**Comment by gmetais** [comment]
Hi and sorry for the late answer.

It seems to me this domain name does not exist or is part of an intranet. Can you please copy me the URL ?

**Comment by gmetais** [comment]
Closing a duplicate (#169).
