### ISSUE TITLE
Google analytics code is present even when there is no Goggle analytics  ID

### ISSUE THREAD

**Issue by MagicFab** [gmetais/YellowLabTools#247]
In the following files a Google analytics ID can be configured to automatically include the corresponding tracker elsewhere:

- server_config/settings-prod.json
- server_config/settings.json

If no value is provided for googleAnalyticsId, the corresponding code should not be loaded.

**Comment by gmetais** [comment]
You're right, we shouldn't load analytics.js at all when it's not needed.

`if('@@googleAnalyticsId'.indexOf('UA-')===0)` should be before the async script call.

I'll work on it when I get a moment, or maybe you can send a pull request.

**Comment by gmetais** [comment]
Fixed by #260. Thanks!
