### ISSUE TITLE
Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by JyotiPrakashMallick** [gmetais/YellowLabTools#248]
PS D:\YellowLabTools> node bin/server.js
D:\YellowLabTools\node_modules\bindings\bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → D:\YellowLabTools\node_modules\lwip\build\lwip_image.node
 → D:\YellowLabTools\node_modules\lwip\build\Debug\lwip_image.node
 → D:\YellowLabTools\node_modules\lwip\build\Release\lwip_image.node
 → D:\YellowLabTools\node_modules\lwip\out\Debug\lwip_image.node
 → D:\YellowLabTools\node_modules\lwip\Debug\lwip_image.node
 → D:\YellowLabTools\node_modules\lwip\out\Release\lwip_image.node
 → D:\YellowLabTools\node_modules\lwip\Release\lwip_image.node
 → D:\YellowLabTools\node_modules\lwip\build\default\lwip_image.node
 → D:\YellowLabTools\node_modules\lwip\compiled\6.11.1\win32\x64\lwip_image.node
    at bindings (D:\YellowLabTools\node_modules\bindings\bindings.js:93:9)
    at D:\YellowLabTools\node_modules\lwip\lib\Image.js:3:41
    at Object.<anonymous> (D:\YellowLabTools\node_modules\lwip\lib\Image.js:16:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

^any thought on the above issue ?

**Comment by ousamabenyounes** [comment]
Hi @JyotiPrakashMallick,

Did you follow installation guide?
https://github.com/gmetais/YellowLabTools/wiki/Install-your-private-server

It seems that the node_module directory doesn't exist.
If you want to install it you should first run "npm install"

Regards,
Ousama.

**Comment by JyotiPrakashMallick** [comment]
@ousamabenyounes . It is installed & I follow the process as mentioned in the URL. I really don't know what went wrong ? Any thought on this. I am attaching my folder structure here.
![folderstructure](https://user-images.githubusercontent.com/6301012/33379540-795ab90c-d53e-11e7-9ab4-91b1a57593ed.PNG)

**Comment by ousamabenyounes** [comment]
I can recommand you to use Docker image
Really easy to install and maybe you'll be able to use YLT on your local computer without any issue... 

https://github.com/jguyomard/docker-yellowlabtools

**Comment by JyotiPrakashMallick** [comment]
@ousamabenyounes I ma able to install docker and I am able to test my application. My web application have log in and allow me to perform action.

So to do this how can achieve this work flow. Like login then performance action and then log out and I want to measure the health in three phase.
While launching URL , then after log in and then after log out. Can you please provide some thought on this ?

**Comment by gmetais** [comment]
Hi @JyotiPrakashMallick,

Sorry, YLT doesn't come with a built-in database writer. You need to write your own wrapper with Node using YLT's [Node module](https://github.com/gmetais/YellowLabTools/wiki/NodeJS-module), or with any other language using the [cli](https://github.com/gmetais/YellowLabTools/wiki/Command-Line-Interface) or the [API](https://github.com/gmetais/YellowLabTools/wiki/Public-API).
