### ISSUE TITLE
Getting bad request while using public api

### ISSUE THREAD

**Issue by JyotiPrakashMallick** [gmetais/YellowLabTools#249]
I am sending the following parameter through postman and I am getting "Bad Request" as result.
header 
"Content-Type": application/json
Body
{
  "url": "http://url.com",
  "waitForResponse": true
 "device" : desktop
}
![error](https://user-images.githubusercontent.com/6301012/33479880-ce49221a-d6b4-11e7-8154-264b4332c840.PNG)

any thoughts on this ?

**Comment by gmetais** [comment]
Hi!

Take care when writing the JSON, it's very sensitive :) There's a comma missing on your second line and "desktop" needs double quotes:

```json
{
"url": "http://url.com",
"waitForResponse": true,
"device" : "desktop"
}
```
