### ISSUE TITLE
How this grades were calculating ?

### ISSUE THREAD

**Issue by JyotiPrakashMallick** [gmetais/YellowLabTools#250]
Is there any metrics or is there any range on which YLT decides the grade ? If yes can I have the metrics ?

**Comment by gmetais** [comment]
Hi,

The metrics for each rule are here: https://github.com/gmetais/YellowLabTools/blob/master/lib/metadata/policies.js

`isOkThreshold`: you get a 100/100 score
`isBadThreshold`: you get a 0/100 score
