### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by xiaowuming** [gmetais/YellowLabTools#252]
⠇ [0/1] Installing trim-repeated@^1.0.0
WARN node unsupported "node@v9.2.0" is incompatible with yellowlabtools@1.12.3 › imagemin-jpegoptim@5.0.0 › jpegoptim-bin@3.0.0 › bin-build@2.2.0 › download@4.4.3 › got@^5.0.0, expected node@>=0.10.0 <7
✔ Installed 1 packages
✔ Linked 564 latest versions
  ✔ jpegtran pre-build test passed successfully
  ✔ optipng pre-build test passed successfully
  ⚠ The `/home/mapp/test/a/node_modules/_jpegoptim-bin@3.0.0@jpegoptim-bin/vendor/jpegoptim` binary doesn't seem to work correctly
  ⚠ jpegoptim pre-build test failed
  ℹ compiling from source
  ✔ jpegoptim built successfully
PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Removing /home/mapp/test/a/node_modules/_phantomjs-prebuilt@2.1.16@phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1513667248870/phantomjs-2.1.1-linux-x86_64 -> /home/mapp/test/a/node_modules/_phantomjs-prebuilt@2.1.16@phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/mapp/test/a/node_modules/_phantomjs-prebuilt@2.1.16@phantomjs-prebuilt/lib/phantom/bin/phantomjs
make: Entering directory `/home/mapp/test/a/node_modules/_lwip@0.0.9@lwip/build'
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/util.o
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/buffer_worker.o
../src/decoder/buffer_worker.cpp: In constructor ‘DecodeBufferWorker::DecodeBufferWorker(Nan::Callback*, v8::Local<v8::Object>&, buf_dec_f_t)’:
../src/decoder/buffer_worker.cpp:8:58: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
     _height(0), _channels(0), _trans(false), _metadata("") {
                                                          ^
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/jpeg_decoder.o
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/png_decoder.o
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/gif_decoder.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jmemnobs.o
make: cc: Command not found
make: *** [Release/obj.target/lwip_decoder/src/lib/jpeg/jmemnobs.o] Error 127
make: Leaving directory `/home/mapp/test/a/node_modules/_lwip@0.0.9@lwip/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/mapp/.node/lib/node_modules/cnpm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 2.6.32-573.18.1.el6.x86_64
gyp ERR! command "/home/mapp/.node/bin/node" "/home/mapp/.node/lib/node_modules/cnpm/node_modules/npminstall/node-gyp-bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mapp/test/a/node_modules/_lwip@0.0.9@lwip
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
✖ Install fail! Error: post install error, please remove node_modules before retry!
Run "sh -c node-gyp rebuild" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "sh -c node-gyp rebuild" error, exit code 1
    at ChildProcess.proc.on.code (/home/mapp/.node/lib/node_modules/cnpm/node_modules/runscript/index.js:74:21)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
npminstall version: 3.2.1

**Comment by gmetais** [comment]
Hi,

There's a problem with the lwip dependency. You might want to test this pull request: https://github.com/gmetais/YellowLabTools/pull/251 and tell me.

**Comment by gmetais** [comment]
#251 is merged, i'm closing this issue with **lwip**.
