### ISSUE TITLE
Session Management in Yellow Lab Tool

### ISSUE THREAD

**Issue by JyotiPrakashMallick** [gmetais/YellowLabTools#253]
I am sending the following details :
POST http://ylt.com:32768/api/runs  : Docker address where YLT is running
 And in the post data I am sending
POST data:
{
  "url": 
"https://test.com/login.html",
  "waitForResponse": true,
  "Authorization" : "Basic XXXXXXXXXXX",
  "Method": "GET",
  "screenshot":true
}
Our application uses base 64 encoding.

Application URL is not getting authenticated with the auth token provided in the post body.
^Any thoughts on this ?

**Comment by gmetais** [comment]
Hi,

```
"Authorization" : "Basic MDkzNjgyOTBfNmY4MGI1ZDExODU3NTE2Mzo=",
"Method": "GET",
```
are not valid parameters for the API. You need to use `authUser` and `authPass` as specified here: https://github.com/gmetais/YellowLabTools/wiki/Public-API

**Comment by JyotiPrakashMallick** [comment]
@gmetais  how it will identify when to send authuser and authpass ? My application is build on angular js. any thoughts on this ?

**Comment by gmetais** [comment]
Sadly, the tool is not able to submit a login form, it's only able to connect with basic HTTP Auth.

Maybe you can handle this situation with a cookie?

**Comment by JyotiPrakashMallick** [comment]
@gmetais  thank you for the info, let me try with cookie.

**Comment by JyotiPrakashMallick** [comment]
@gmetais our system not used cookie.

**Comment by JyotiPrakashMallick** [comment]
@gmetais  wants to contribute more.

**Comment by gmetais** [comment]
@JyotiPrakashMallick It's either a cookie based session or a basic HTTP Auth. Can't you detect which cookie's in use?
