### ISSUE TITLE
yellowlab.tools website is not working

### ISSUE THREAD

**Issue by ipepe** [gmetais/YellowLabTools#267]
I know it's not related to this tools source code. But Maybe owner didn't notice that website his died? @gmetais did You notice?

**Comment by gmetais** [comment]
Oh thanks! It's back online.

I still don't understand why the server server crashes sometimes. I'm going to change it soon and hope it will fix the issue.

**Comment by ipepe** [comment]
@gmetais I recommend You uptimerobot.com, it's free and good quality service for monitoring. Also if You need some help with servers let me know.

**Comment by gmetais** [comment]
Thanks @ipepe. I'm already using Pingdom to send me notifications, but this downtime was precisely during a long night bus trip in Colombia without wifi :/

Thanks for your help proposal, I'm taking good notes :)

**Comment by ipepe** [comment]
@gmetais btw. thank You, creating this great tool!
