### ISSUE TITLE
Not able to test an application on local machine

### ISSUE THREAD

**Issue by JyotiPrakashMallick** [gmetais/YellowLabTools#296]
I have hosted both my application and YLT(private instance) on the local machine. When I am trying to test the application it is giving me test failed and with a code `3221225477`. 

How to test your local application.

![Capture](https://user-images.githubusercontent.com/6301012/54350066-88644700-4672-11e9-8483-0daee881bde7.PNG)

**Comment by gmetais** [comment]
Hi,
YellowLabTools has problems on Windows computers. This issue is reported here: #150.
Do you have access to a Linux machine?
I'm closing this issue, please give us any additional feedback in #150.
