### ISSUE TITLE
Persistent CSS Syntax errors in tests after being fixed

### ISSUE THREAD

**Issue by AfonsoFG** [gmetais/YellowLabTools#297]
A couple days ago I ran some tests and got the following output for the category CSS Syntax Errors 
```
@keyframes missing '{' https://ecocampus.utad.pt/assets/css/app.css @ 4488:29 (Check on the W3C validator)
property missing ':' https://ecocampus.utad.pt/assets/css/app.css @ 4490:10 (Check on the W3C validator)
missing '}' https://ecocampus.utad.pt/assets/css/app.css @ 4490:10 (Check on the W3C validator)
selector missing https://ecocampus.utad.pt/assets/css/app.css @ 4490:10 (Check on the W3C validator)
````

Indeed I had those errors and fixed them but all the following tests still report. W3C Validator reports those errors as gone.

The site tested was https://ecocampus.utad.pt

**Comment by gmetais** [comment]
Hi Afonso,
It looks like the parser doesn't like the comment in the following lines:

```
@-webkit-keyframes rotating /* Safari and Chrome */
{
    from {
        transform: rotate(0deg)
    }
    to {
        transform: rotate(360deg)
    }
}
```

It's obviously a bug in the tool. Thank you for reporting the bug!

**Comment by AfonsoFG** [comment]
No problem! Anytime.

Thanks for helping me figuring it out!
