### ISSUE TITLE
PhantomJS error 254

### ISSUE THREAD

**Issue by vyskoczilova** [gmetais/YellowLabTools#299]
Any idea, why this site fails with PhantomJS error - _Test failed, Error 254: page loading failed in PhantomJS_? 

https://whoopdedoo.me

Thanks a lot!

**Comment by gmetais** [comment]
Hi @vyskoczilova,
The website does a JavaScript redirection to https://whoopdedoo.me/en/ which is causing the issue. Running the test on the final URL directly does the job: https://yellowlab.tools/result/fgx2g8zoe2
Sorry for the issue!
May I close this ticket?

**Comment by vyskoczilova** [comment]
@gmetais Hi, thanks I see - maybe you could add a note that there might be a redirect because of JS detecting language :) Thanks a lot and closing the ticket :)
