### ISSUE TITLE
SSL issue with Phantomas? Failed Page Load.

### ISSUE THREAD

**Issue by anselmh** [gmetais/YellowLabTools#38]
Hi,

just tried to analyze my website and it failed due to not being able to load the page.
http://yellowlab.tools/queue/dzq1ogv01z

     Test failed
     Error 254: page loading failed in Phantomas

I use SSL via CloudFlare on Github Pages, just for the technical record.

**Comment by gmetais** [comment]
Hi @anselmh, thanks for reporting.

It looks like it's a problem with PhantomJS. It just won't load the page and I can't find the reason. Your SSL configuration looks good.

Do you have the possibility to test on a non-SSL instance, to check if the problem comes from it?

**Comment by anselmh** [comment]
SSL is the issue, without SSL the tool works fine again. http://yellowlab.tools/result/dzq75bsi3f 
It is very likely a Phantomas issue with this style of SSL configuration as other testing tools using the same method fail, too.

**Comment by gmetais** [comment]
Ok, thank you for the test. I hope the much expected PhantomJS v2 will correct this.

( Here is a tool for analyzing SSL connection and everything looks alright : https://www.ssllabs.com/ssltest/analyze.html?d=helloanselm.com&s=104.28.6.74 )

**Comment by anselmh** [comment]
Hey, are you calling phantomjs with `--ssl-protocol=any` option? It might help if you don’t. There’s also `--ignore-ssl-errors=true` but I wouldn’t recommend setting this on a live site.

**Comment by gmetais** [comment]
`--ssl-protocol` is `any` and `--ignore-ssl-errors` is `false` on YLT.
However I tested all the different values without success.

**Comment by anselmh** [comment]
Okay, then it might be an issue with PhantomJS itself. Let’s hope for an update soon then :) Feel free to close the issue.
