### ISSUE TITLE
Is the recommended Docker image outdated?

### ISSUE THREAD

**Issue by kevinfarrugia** [gmetais/YellowLabTools#405]
Hi. I have been using the web version of the tool and today I tried to set up a local instance using the [docker image](https://github.com/ousamabenyounes/docker-yellowlabtools). However this image connects to v2.0.0 of YLT instead of the later v.3.0.1.

Are you aware if the docker image is outdated and if there is any work already in progress to update it?

I have started working on an updated Dockerfile that connects to the [YellowLabTools-server](https://github.com/YellowLabTools/YellowLabTools-server) and updated some minor configurations, so I would be happy to create a PR once I get it to work—currently encountering some issues with launching Phantomas.

**Comment by gmetais** [comment]
Hi Kevin,

Thanks for your work on updating the docker image.
We didn't rush on updating the docker because it looks like we still have a random issue with YLT v3, especially when ran from a container: https://github.com/macbre/phantomas/issues/1337

I've managed to fix it very temporarily (unstable on the long term) on my local docker with this line in the Dockerfile: 
`RUN sed -i '35 s/^/\/\//' node_modules/phantomas/lib/browser.js`

**Comment by kevinfarrugia** [comment]
Do you get the same issue on my [branch](https://github.com/kevinfarrugia/docker-yellowlabtools/tree/update-dockerfile)?

The [issue](https://github.com/macbre/phantomas/issues/1337#issue-2052596409) uses Node v20 that I have not yet tried (my image uses Node 18). In the comments there is also mention that it could be related to the complexity of the tested website. Do you have a complex website that I could test against?

Anything else I could do to replicate the issue? So far I have only tested this locally using Docker version 25.0.1.

**Comment by gmetais** [comment]
Sorry I miss time right now to test your branch, but I can answer the second question: the website on which crashes are the most frequent is https://www.lepoint.fr/.

**Comment by kevinfarrugia** [comment]
It seems to work well (tested the same page 10 times using _Test Again_), but if the issue is sporadic I cannot guarantee it will not happen again. I did notice that some tests take longer than others, but eventually it completes. (screenshot doesn't work)

![localhost_8383_result_gt6qwixxzg](https://github.com/YellowLabTools/YellowLabTools/assets/8075326/b85ac947-4564-4076-a832-8af0639aab46)

**Comment by kevinfarrugia** [comment]
This issue can be closed once https://github.com/ousamabenyounes/docker-yellowlabtools/pull/40 is merged.

**Comment by kevinfarrugia** [comment]
Closing as we have published [yellowlabtools V3 to Docker Hub](https://hub.docker.com/r/ousamabenyounes/yellowlabtools/tags).
