### ISSUE TITLE
Phantomas failed: net::ERR_NAME_NOT_RESOLVED at http://mysite.local:90/

### ISSUE THREAD

**Issue by assendk** [gmetais/YellowLabTools#406]
I want to test a local site. Linux/Ubuntu machine but takes this message
Phantomas failed: net::ERR_NAME_NOT_RESOLVED at http://mysite.local:90/

The site itself is in WordPress docker and not a LAMP
- An SSL is not added so the URL is HTTP instead of https.
- the docker response on port 90. Tried a few instances with different ports without success
- mysite.local is added to the /etc/hosts

Please help with debugging

**Comment by gmetais** [comment]
What happens if you run `curl http://mysite.local:90/` ?

**Comment by assendk** [comment]
The full page is rendered

```
adk-A5:~$ curl http://cort****.local:90
<!DOCTYPE html>
<html lang="en-GB" class="no-js scheme_dark">
<head>
...
```

**Comment by gmetais** [comment]
Ok, that's a bit strange. YLT is supposed to handle this just the way curl does. I've tried to reproduce with an http website hosted on my machine with a host and it works fine. The only difference is my test website is not hosted in a docker container, but it should be fine.

**Comment by kevinfarrugia** [comment]
@assendk How are you running YLT? Are you running a local instance?

**Comment by assendk** [comment]
> @assendk How are you running YLT? Are you running a local instance?
Yes local instance by using the presented command
`docker run --privileged -p 8383:8383 ousamabenyounes/yellowlabtools `
I think that the problem is in my WordPress docker/yaml and the internal port mapping because there is no problem with scanning external sites. I can share the yaml if someone is interested

**Comment by kevinfarrugia** [comment]
The Docker image running YLT does not have access to your host network by default. Try running it with the [`--network=host`](https://docs.docker.com/network/network-tutorial-host/) argument.

```diff
- docker run --privileged -p 8383:8383 ousamabenyounes/yellowlabtools 
+ docker run --network host --privileged -p 8383:8383 ousamabenyounes/yellowlabtools 
```

We also published a new version of the Docker image yesterday, so I suggest pulling the latest version (v3.0.1):

```
docker pull ousamabenyounes/yellowlabtools
```

Let me know if that works for you.

**Comment by assendk** [comment]
It works now!
Thanks for your time and thanks for the great tool. I obviously lack Dockers' knowledge.
It is tested with the latest version (v3.0.1).
Local run of ousamabenyounes/yellowlabtools, local docker compose WordPress env + local host/virtual domain:port.
