### ISSUE TITLE
Test failed Error 254: page loading failed in Phantomas

### ISSUE THREAD

**Issue by afvalzak** [gmetais/YellowLabTools#44]
I keep getting 
Test failed
Error 254: page loading failed in Phantomas

with 2 sites (https://www.nedtrack.nl and https://www.nedsoft.nl) 
is this a problem with my website or with the tool?

**Comment by gmetais** [comment]
Hi afvalzak, thank you for reporting.

I made a few tests and it seems to be a problem with PhantomJS, the headless browser used by YellowLabTools. There seems to be some HTTPS problems sometimes. Everyone is waiting for PhantomJS 2.0, and i hope it's going fix this kind of failures.

Sorry for not being able to help you more, but you don't have to worry about your websites :)

What server or proxy or CDN are you using for the SSL?

**Comment by afvalzak** [comment]
Both SSL certificates are provided by RapidSSL

OCSP Responder: URI: http://gv.symcd.com
CA Issuers: URI: http://gv.symcb.com/gv.crt

Is this helpful? 

The server runs plesk and I'm not the hoster so I'd have to ask them if you need more information.

**Comment by gmetais** [comment]
I'm not very aware about SSL configuration :/ I was asking because someone with the same problem (#38) was using CloudFlare and i thought it could be the same problem.

Have a look at this SSL auditing tool : https://www.ssllabs.com/ssltest/analyze.html?d=nedsoft.nl
You might show this to your hosting provider but i can't guarantee that it's going to fix PhantomJS issues...

The other domain has a better score : https://www.ssllabs.com/ssltest/analyze.html?d=nedtrack.nl

**Comment by afvalzak** [comment]
Ah, Thanks for the info, I'll send this to the hoster even if it won't  fix the problem, seems a bit useless to have a SSL certificate and still not be secure ;)

**Comment by gmetais** [comment]
Still better than nothing. At least the data is encrypted !

I'll keep the issue open so people can come post their failing urls, maybe we're going to find similarities between the SSL configurations.

**Comment by wforums** [comment]
I'm getting the same issue, but my certificates should be ok (A+ on ssllabs).

Can you let me know what could be the issue?

The site is https://www.zittingskalender.be

**Comment by gmetais** [comment]
Hi @wforums,

I can't tell why it fails, these PhantomJS issues with HTTPS are very unclear to me.

The strangest thing is that it's working on my computer's dev instance though it's using the same PhantomJS version. Could it be a linux-only problem (my computer is a mac).

**Comment by wforums** [comment]
@gmetais,

thanks for the quick reply. I just checked my site with phantomJS myself, using a simple example from the Quick Start sessions, and it's throwing a TypeError (although the code is working perfectly fine in regular browsers).

Could this be the cause of the error too on the YellowLabTools?

**Comment by gmetais** [comment]
No, I don't believe it is the cause. This is another problem.

You are using the Element and the Node interfaces but PhantomJS doesn't seem to know them (undefined). These errors deserve some more debugging too.

**Comment by kkwoker** [comment]
I'm experiencing the same issue with https://selfserve.publicmobile.ca/ 
Did anyone get a chance to figure the cause?

**Comment by gmetais** [comment]
Hi @kkwoker,

The strange thing is that your URL is working on my dev instance of YLT (which is a Mac). It fails on the Ubuntu production server for a reason I can't understand. Same thing for one of the two urls of @afvalzak.

Maybe a linux only SSL problem...

**Comment by Zolmeister** [comment]
Another broken site: https://zorium.org/

**Comment by gmetais** [comment]
Still no clue on this issue...
Cloudflare seems to be a part of the problem.

**Comment by gmetais** [comment]
Someone told me I could update the certificates on the Ubuntu server with `update-ca-certificates` but no improvements. If anyone got any other ideas...

**Comment by ndarville** [comment]
Same for <https://hafniatimes.com>. It’s not the CDN/HTTPS, because <https://ndarville.com> uses the same.

It’s hosted on GitHub (vs S3 for ndarville.com), which is the only difference I can think of.

**Comment by gmetais** [comment]
Good news, I tested all of the above URLs with PhantomJS 2 and they're all working fine!

I make primary tests on this branch: https://github.com/gmetais/YellowLabTools/tree/phantomjs2
Unfortunately, PhantomJS 2 is not working yet on Mac.

**Comment by Rinfore** [comment]
another broken site: http://danielwong.tk

**Comment by gmetais** [comment]
Hi @Rinfore,

Thank you for reporting the error.

This is not a https error like the others in this thread. It looks like PhantomJS is redirected to http://danielwong.tk/tablet/index.html
Can you tell me more about the way you redirect tablets to this page, so I can understand what is wrong?

**Comment by Rinfore** [comment]
I'm sorry @gmetais but I am not a web developer. I used Adobe Muse to create that website. I merely created a desktop version, tablet version, and mobile version. I suspect it redirects based on resolution. I wish I could help you more.

**Comment by gmetais** [comment]
I managed to force desktop view and avoid redirection, by adding "devicelock=desktop" as a cookie (in advanced settings).

Here are the results: http://yellowlab.tools/result/e6l7rsfp2l

**Comment by gmetais** [comment]
Hi, I managed to update PhantomJS to version 2 on the public instance.
Which means all of the above HTTPS issues are fixed! :tada: 

The redirection issue (http://danielwong.tk) is not going to be fixed, but I opened this issue in the phantomas project: https://github.com/macbre/phantomas/issues/550
