### ISSUE TITLE
Test failed  Error: JPEG decoding error

### ISSUE THREAD

**Issue by ipepe** [gmetais/YellowLabTools#53]
I wanted to test some website because it was ultra slow. And got an error :smile:  now I know probably why it was slow. Could u see what is the problem? Im not owner of website and also, it's in polish.
Tested url:   http://www.zajadam.pl/przepisy-zupy/rosol-domowy

**Comment by gmetais** [comment]
Hi @ipepe !

The page is very, very, very long and it seems to be a problem for the screenshot generation.

I have a few ideas to fix the problem, but the most important is to make the error silent. The rest of the report should complete even if the screenshot couldn't be generated.

Thank you for reporting the issue!

**Comment by ipepe** [comment]
Shortlink to test: http://yellowlab.tools/queue/e14d8k779b

**Comment by gmetais** [comment]
Partially fixed by #76 : the test completes even if the screenshot generation fails

**Comment by gmetais** [comment]
I won't fix the screenshot generation on very very long pages. Closing.
