### ISSUE TITLE
Local install returns TypeError: Bad Argument with all requests

### ISSUE THREAD

**Issue by pizatski** [gmetais/YellowLabTools#64]
Hi team,

I ran through the local installation of Yellow Lab Tools using the Node version of the installation and every url request returns me a ```TypeError: Bad argument```.

I'm not sure if this has to do with using the latest node dependencies after running npm install.

Here's the pertinent information for the request and response:
1) Request headers to /api/runs/[random]
```
GET /api/runs/e26gjdwz92 HTTP/1.1
Host: localhost:8383
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36
Referer: http://localhost:8383/queue/e26gjdwz92
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
```
2) Response Headers
```
HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Vary: Origin, Accept-Encoding
Content-Type: application/json; charset=utf-8
Content-Length: 285
ETag: W/"11d-54f96413"
Date: Thu, 02 Apr 2015 15:16:38 GMT
Connection: keep-alive
```
3) Actual Response
```
{
  "runId": "e26gjdwz92",
  "params": {
    "url": "http://localhost.domain.com:9001",
    "waitForResponse": false,
    "partialResult": null,
    "screenshot": true,
    "jsTimeline": true
  },
  "status": {
    "statusCode": "failed",
    "error": "TypeError: Bad argument"
  }
}
```
Also, in queueCtrl.js, I am throwing an error instead of allowing the view to just render. Here's the stacktrace from the console:
```
Error
    at Runs.get.$scope.notFound (queueCtrl.js:26)
    at angular-resource.js:627
    at angular.js:13248
    at n.$get.n.$eval (angular.js:14466)
    at n.$get.n.$digest (angular.js:14282)
    at n.$get.n.$apply (angular.js:14571)
    at l (angular.js:9698)
    at M (angular.js:9888)
    at XMLHttpRequest.F.onload (angular.js:9829)
```

I also see the TypeError being thrown in browserify, so maybe there's an update there that breaks something?

**Comment by gmetais** [comment]
Hi @pizatski 

I'll try to reproduce your bug tomorrow, but what do you mean by "using the latest node dependencies after running npm install" ?

**Comment by gmetais** [comment]
I installed a fresh new instance on my computer and everything works as expected.

Could you please try to launch a run from the CLI, to see if the problem comes from the core or from the API?

```shell
node bin/cli.js www.google.com
```

**Comment by gmetais** [comment]
@pizatski 
Any news?

**Comment by pizatski** [comment]
Sorry for the drop in communications. A few other folks here were able to
install with no issues as well which means it's an issue with my setup.
I'll give it a shot again from the start, but in the meantime let's close
this issue.

Thanks for your time and attention. Great product!!

**Comment by gmetais** [comment]
Ok!
