### ISSUE TITLE
Proxy setting in YLT / PhantomasWrapper.js

### ISSUE THREAD

**Issue by abhishek0001** [gmetais/YellowLabTools#78]
Hi, 
I tried running YLT in a corporate environment behind a firewall with the git based setup. I kept running into an access denied error.

Adding an option to accept the proxy parameter in PhantomasWrapper.js as a workaround works for me. What is the correct way to set up the corporate proxy with YLT, not sure if this is a bug/missed option?

Thanks
P.S. Can you mention the msvs_version=2013 option to npm install for Windows users for node-gyp setup  somewhere in the documentation. Git, bower, npm all need additional proxy set up configuration params too.

**Comment by gmetais** [comment]
Hi @abhishek0001!

You are right, there's no way to set up a proxy for the moment.

Phantomas can work with proxy settings. But it doesn't send the settings to analyze-css. Analyze-css re-downloads the CSS files one by one, so an improper proxy setting will skip most of the CSS files and give a erroneous score.

I opened this issue: https://github.com/macbre/phantomas/issues/500
I think we'd better wait for a fix (or fix this issue ourself) before adding the option in YLT.

------

About the installation process for Windows, I don't really understand what this msvs_version refers to (I'm not a Windows user). Do you mind editing the Wiki to add this mention? That would be great!
You could also add a small chapter about proxy settings on Git, bower and npm.

**Comment by abhishek0001** [comment]
Thanks for the quick answer. I will try and update the wiki soon.

For windows installation, YLT uses lwip package which in turn uses node-gyp. node-gyp needs recompilation and needs the msvs_version=2013 flag for locating C++ compiler/libs. 

Links for more details:
https://www.npmjs.com/package/lwip
https://github.com/TooTallNate/node-gyp#installation
https://github.com/TooTallNate/node-gyp/issues/339
http://stackoverflow.com/questions/14278417/cannot-install-node-modules-that-require-compilation-on-windows-7-x64-vs2012

**Comment by macbre** [comment]
@gmetais, it took a while, but it's finally there - https://github.com/macbre/phantomas/pull/663

**Comment by gmetais** [comment]
You rule @macbre !

**Comment by gmetais** [comment]
Fixed by #213.
