### ISSUE TITLE
Test failed : Error 255: Phantomas error

### ISSUE THREAD

**Issue by caiuspupus** [gmetais/YellowLabTools#99]
Hi,

I ran some tests of some websites and I got this error for the following:
- http://www.dna.fr
- http://www.lejsl.com
- http://www.lalsace.fr

For information purpose, I ran tests on other web tools for these sites and they worked well.

Thanks in advance for your help on this.

**Comment by gmetais** [comment]
Hi @caiuspupus!

Thank you for reporting this bug.
As it's working fine on my local instance of YLT,  debugging is going to be difficult.

All I can tell you from what I see on my local instance is that these 3 websites have bad scores (0/100).

**Comment by gmetais** [comment]
See #137.
